### PR TITLE
Added Milestone Dependency

### PR DESCRIPTION
**Pull request by acl-24**
allow changing the dependent tasks and milestones when editing or creating milestones

### CODE REVIEW

**Comment by ElenaArnold** [comment]
Do we need to be able to set dependent tasks in the edit milestone form? I think this is covered when we set the tasks parent when we create it.

Similarly the milestone should be able to optionally have a parent when you create it and it is not necessary to have dependent milestone selection in the edit form but instead change/set the parent.

Unless there is something I am not thinking of?

**Comment by acl-24** [comment]
Yeah the main reason im doing it is because of the FR namely
Add.Milestone: The system provides a way for the user to create a new milestone within a project. This milestone must be within a Project and it can contain one or more Tasks. The milestone may have one or more Milestones/Tasks as dependencies.
Edit.Milestone: The system provides a way for the user to edit a milestone they or another user created. The user is able to edit any of the fields they could set when adding a milestone.
where it specified that we need to have dependent milestones and tasks, if you guys think that it is not necessary, we dont have to include it

**Comment by acl-24** [comment]
also similar thing for tasks, which i was working on till the migration lol

**Comment by ElenaArnold** [comment]
My point is though that you set dependent tasks/milestones by setting the parent, otherwise you have to do a lot of confilct checking.

For milestones you should be able to set any milestone as a parent or it may have no parent.
For tasks you should be able to set a milestone or a task as a parent.

**Comment by ElenaArnold** [comment]
For example I have Task A whose parent is Milestone A, but I was able to set Task A as a dependent task of New Milestone, so now Task A has two parents which doesn't make sense.

**Comment by acl-24** [comment]
ok i get ur point, the fr says "one or more Milestones/Tasks as dependencies", by this we are saying it can only have 1 parent task/milestone and multiple children task/milestone?

**Comment by ElenaArnold** [comment]
That was my assumption, but I do see the problem now with the way the backend is currently setup

**Comment by ElenaArnold** [comment]
If it works, it's fine. I maybe just needed to think about it differently - i.e. to do  Task A we need to do Task B, Milestone X, etc but it is not necessarily a parent. Is that what you were thinking originally?

**Comment by acl-24** [comment]
> If it works, it's fine. I maybe just needed to think about it differently - i.e. to do Task A we need to do Task B, Milestone X, etc but it is not necessarily a parent. Is that what you were thinking originally?

Yeah i guess another way of thinking about it is that a task or milestone can have multiple "parents", so it might be a subtask that is required by multiple tasks to complete. 

But i think you are right about the conflict checking part, as there could indeed be transpositions and cycles

**Comment by yismailuofa** [comment]
I think we still need this feature, the depdencies are so that you can see what a task is blocked on and visualized in the graph.

**Comment by acl-24** [comment]
sounds good ill keep working on the task side

will pull new pr under new branch with merge confilcts resolved

**Pull request closed without merging**
